; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[] = "drupal"
; Modules
projects[] = "ctools"
projects[] = "content_access"

projects[] = "date"
projects[] = "devel"
projects[] = "diff"
projects[] = "entity"
projects[] = "entityreference"
projects[] = "features"
projects[] = "fences"
projects[] = "file_entity"
projects[] = "libraries"
projects[] = "link"
projects[] = "media"
projects[] = "media_youtube"
projects[] = "mollom"
projects[] = "navbar"
projects[] = "pathauto"
projects[] = "strongarm"
projects[] = "token"
projects[] = "views"
projects[] = "wysiwyg"
; Themes
projects[] = "zen"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = "get"
libraries[backbone][download][url] = "http://backbonejs.org/backbone-min.js"
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.4.7/ckeditor_4.4.7_standard.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[mediaelement][download][type] = "get"
libraries[mediaelement][download][url] = "http://github.com/johndyer/mediaelement/zipball/master"
libraries[mediaelement][directory_name] = "mediaelement"
libraries[mediaelement][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[modernizr][download][type] = "get"
libraries[modernizr][download][url] = "blob:http://modernizr.com/3e7c9a4f-6320-6846-9a1b-026f0ed6c14f"
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = "get"
libraries[underscore][download][url] = "https://github.com/jashkenas/underscore/archive/1.5.2.zip"
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

